<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <AssemblyName>PotionCraftAPMod</AssemblyName>
    <Product>Potion Craft AP Client</Product>
    <Version>0.0.1</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>PotionCraftAPMod</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.0" />
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
    <PackageReference Include="HarmonyX" Version="2.14.0" />
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="UnityEngine.Modules" Version="2023.1.13" IncludeAssets="compile" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="PotionCraft.Core">
      <HintPath>lib\PotionCraft.Core.dll</HintPath>
    </Reference>
    <Reference Include="PotionCraft.DataBaseSystem">
      <HintPath>lib\PotionCraft.DataBaseSystem.dll</HintPath>
    </Reference>
    <Reference Include="PotionCraft.InputSystem">
      <HintPath>lib\PotionCraft.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="PotionCraft.ManagerSystem">
      <HintPath>lib\PotionCraft.ManagerSystem.dll</HintPath>
    </Reference>
    <Reference Include="PotionCraft.SceneLoader">
      <HintPath>lib\PotionCraft.SceneLoader.dll</HintPath>
    </Reference>
    <Reference Include="PotionCraft.Scripts">
      <HintPath>lib\PotionCraft.Scripts.dll</HintPath>
    </Reference>
    <Reference Include="PotionCraft.Settings">
      <HintPath>lib\PotionCraft.Settings.dll</HintPath>
    </Reference>
    <Reference Include="PotionCraft.ShaderEffects">
      <HintPath>lib\PotionCraft.ShaderEffects.dll</HintPath>
    </Reference>
    <Reference Include="PotionCraft.SoundSystem">
      <HintPath>lib\PotionCraft.SoundSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.InputSystem">
      <HintPath>lib\Unity.InputSystem.dll</HintPath>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>lib\Unity.TextMeshPro.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputModule">
      <HintPath>lib\UnityEngine.InputModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>lib\UnityEngine.UI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
